openapi: 3.0.3
info:
  title: Terms
  description: System Info about terms
  version: 1.0.0
servers:
  - url: 'http://localhost:85/api'
    description: local

# securitySchemes:
#   BearerToken:
#     type: http
#     scheme: bearer
#     bearerFormat: JWT
paths:

  /terms:
    get:
      tags:
        - Terms
      summary: Get all terms
      responses:
        '200':
          description: Successful displayed all terms
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                example:
                  - id: 1
                    name: test
                    created_at: "2024-01-31T08:46:59.000000Z"
                    updated_at: "2024-01-31T08:46:59.000000Z"
                  - id: 2
                    name: test1
                    created_at: "2024-01-31T08:46:59.000000Z"
                    updated_at: "2024-01-31T08:46:59.000000Z"
                  - id: 3
                    name: test2
                    created_at: "2024-01-31T08:46:59.000000Z"
                    updated_at: "2024-01-31T08:46:59.000000Z"

  /terms/last:
    get:
      tags:
        - Terms
      summary: Get last terms
      responses:
        '200':
          description: Successful displayed last terms
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                      example: 1
                    name:
                      type: string
                      example: test
                    created_at:
                      type: string
                      example: "2024-01-31T08:46:59.000000Z"
                    updated_at:
                      type: string
                      example: "2024-01-31T08:46:59.000000Z"

