openapi: 3.0.3
info:
  title: Complaints
  description: Complaints
  version: 1.0.0
servers:
  - url: 'http://localhost:85/api'
    description: local

# securitySchemes:
#   BearerToken:
#     type: http
#     scheme: bearer
#     bearerFormat: JWT
paths:

  /complaints:
    get:
      tags:
        - Complaints
      summary: Get all complaints
      parameters:
        - in: query
          name: causer_id
          schema:
            type: integer
            example: 1
          required: false
        - in: query
          name: author_id
          schema:
            type: integer
            example: 1
          required: false
        - in: query
          name: causer_type
          schema:
            type: string
            enum:
              - vacancy
              - candidate
              - recruiter
              - company
          required: false
        - in: query
          name: cause_message
          schema:
            type: string
            # enum:
            #   - needed message
            #   - needed message
            example: 'Bad words'
          required: false
        - in: query
          name: read_status
          schema:
            type: string
            enum:
              - read
              - unread
          required: false
        - in: query
          name: resolve_description
          schema:
            type: string
          required: false
        - in: query
          name: resolve_message
          schema:
            type: string
            # enum:
            #   - needed message
            #   - needed message
            example: 'Banned candidate. Thanks for help!'
          required: false
        - in: query
          name: cause_description
          schema:
            type: string
          required: false
        - in: query
          name: resolver_id
          schema:
            type: integer
            example: 16
          required: false
        - in: query
          name: assignee_id
          schema:
            type: integer
          required: false
        - in: query
          name: assignee_id
          schema:
            type: integer
            example: 16
          required: false
        - in: query
          name: resolved_at_from
          schema:
            type: string
            format: date
            example: 2024-02-21 11:24:50
          required: false
        - in: query
          name: resolved_at_to
          schema:
            type: string
            format: date
            example: 2024-02-21 11:24:54
          required: false
        - in: query
          name: created_at_from
          schema:
            type: string
            format: date
            example: 2024-02-21 11:24:50
          required: false
        - in: query
          name: created_at_to
          schema:
            type: string
            format: date
            example: 2024-02-21 11:24:54
          required: false

      responses:
        '200':
          description: Successful displayed notification
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                    format: int32
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        uuid:
                          type: string
                        author_id:
                          type: integer
                          format: int32
                        causer_id:
                          type: integer
                          format: int32
                        causer_type:
                          type: string
                        cause_message:
                          type: string
                        resolve_message:
                          type: string
                        resolve_description:
                          type: string
                        cause_description:
                          type: string
                        resolver_id:
                          type: integer
                          format: int32
                        assignee_id:
                          type: integer
                          format: int32
                        resolved_at:
                          type: string
                        read_at:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                  first_page_url:
                    type: string
                  from:
                    type: integer
                    format: int32
                  last_page:
                    type: integer
                    format: int32
                  last_page_url:
                    type: string
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                        active:
                          type: boolean
                  next_page_url:
                    type: string
                    format: nullable
                  path:
                    type: string
                  per_page:
                    type: integer
                    format: int32
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                  total:
                    type: integer
                    format: int32
    post:
      tags:
        - Complaints
      summary: Create complaint
      requestBody:
        content:
          application/json:
            schema:
              properties:
                author_id:
                  type: integer
                  format: int32
                causer_type:
                  type: string
                causer_id:
                  type: integer
                  format: int32
                cause_message:
                  type: string
                cause_description:
                  type: string


      responses:
        '201':
          description: Successful created notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  causer_type:
                    type: string
                  causer_id:
                    type: integer
                    format: int32
                  cause_message:
                    type: string
                  cause_description:
                    type: string
                  author_id:
                    type: integer
                    format: int32
                  uuid:
                    type: string
                  updated_at:
                    type: string
                  created_at:
                    type: string

  /complaints/{id}/assign:
    patch:
      tags:
        - Complaints
      summary: Assign admin to resolving complaint
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
            example: 9b6372e2-5a26-4a42-9661-ad604d7810be
          required: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                assignee_id:
                  type: integer
                  format: int32
                  example: 16

      responses:
        '200':
          description: Successful assigned user to resolving complaint
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  author_id:
                    type: integer
                    format: int32
                  causer_id:
                    type: integer
                    format: int32
                  causer_type:
                    type: string
                  cause_message:
                    type: string
                  resolve_message:
                    type: string
                  resolve_description:
                    type: string
                  cause_description:
                    type: string
                  resolver_id:
                    type: integer
                    format: int32
                  assignee_id:
                    type: integer
                    format: int32
                  resolved_at:
                    type: string
                  read_at:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string

  /complaints/{id}:
    get:
      tags:
        - Complaints
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: 9b638838-ebc2-4746-a8ab-67122e3c7d7d
          required: true
      summary: Get and read complaint
      responses:
        '200':
          description: Successful displayed and read complaint
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  author_id:
                    type: integer
                    format: int32
                  causer_id:
                    type: integer
                    format: int32
                  causer_type:
                    type: string
                  cause_message:
                    type: string
                  resolve_message:
                    type: string
                    format: nullable
                  resolve_description:
                    type: string
                    format: nullable
                  cause_description:
                    type: string
                  resolver_id:
                    type: string
                    format: nullable
                  assignee_id:
                    type: string
                    format: nullable
                  resolved_at:
                    type: string
                    format: nullable
                  read_at:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string

  /complaints/{id}/unassign:
    patch:
      tags:
        - Complaints
      summary: Unassign admin to resolving complaint
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
            example: 9b6372e2-5a26-4a42-9661-ad604d7810be
          required: true
      responses:
        '200':
          description: Successful unassigned user from resolving complaint
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  author_id:
                    type: integer
                    format: int32
                  causer_id:
                    type: integer
                    format: int32
                  causer_type:
                    type: string
                  cause_message:
                    type: string
                  resolve_message:
                    type: string
                  resolve_description:
                    type: string
                  cause_description:
                    type: string
                  resolver_id:
                    type: integer
                    format: int32
                  assignee_id:
                    type: string
                    format: nullable
                  resolved_at:
                    type: string
                  read_at:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
  /complaints/{id}/resolve:
    patch:
      tags:
        - Complaints
      summary: Resolve complaint
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
            example: 9b6372e2-5a26-4a42-9661-ad604d7810be
          required: true
      responses:
        '200':
          description: Successful resolved complaint
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  author_id:
                    type: integer
                    format: int32
                  causer_id:
                    type: integer
                    format: int32
                  causer_type:
                    type: string
                  cause_message:
                    type: string
                  resolve_message:
                    type: string
                  resolve_description:
                    type: string
                  cause_description:
                    type: string
                  resolver_id:
                    type: integer
                    format: int32
                  assignee_id:
                    type: string
                    format: nullable
                  resolved_at:
                    type: string
                  read_at:
                    type: string
                    format: nullable
                  created_at:
                    type: string
                  updated_at:
                    type: string
