openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:85/api'
    description: local

# securitySchemes:
#   BearerToken:
#     type: http
#     scheme: bearer
#     bearerFormat: JWT
paths:

  /geo/cities:
    get:
      tags:
        - Cities
      summary: Get all cities
      parameters:
        - in: query
          name: keyword
          required: false
          schema:
            type: string
            example: addanki
        - in: query
          name: page
          required: false
          schema:
            type: integer
            example: 1
            default: 1
        - in: query
          name: per_page
          required: false
          schema:
            type: integer
            example: 10
            default: 15
      responses:
        '200':
          description: Successful displayed searched city or all cities
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: number
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 5
                        state_id:
                          type: number
                          example: 2
                        name:
                          type: string
                          example: addanki
                        status:
                          type: string
                          example: active
                        created_at:
                          type: string
                          format: nullable
                        updated_at:
                          type: string
                          format: nullable
                        deleted_at:
                          type: string
                          format: nullable
                  first_page_url:
                    type: string
                    example: http://localhost:85/api/geo/cities?page=1
                  from:
                    type: number
                    example: 1
                  last_page:
                    type: number
                    example: 1
                  last_page_url:
                    type: string
                    example: http://localhost:85/api/geo/cities?page=1
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean
                  next_page_url:
                    type: string
                    format: nullable
                  path:
                    type: string
                    example: http://localhost:85/api/geo/cities
                  per_page:
                    type: number
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: number
                    example: 1
                  total:
                    type: number
                    example: 1

  /geo/countries:
    get:
      tags:
        - Countries
      summary: Get all countries
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            example: 1
            default: 1
        - in: query
          name: per_page
          required: false
          schema:
            type: integer
            example: 10
            default: 15
      responses:
        '200':
          description: Successful displayed all countries
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: number
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        name:
                          type: string
                          example: afghanistan
                        status:
                          type: string
                          example: active
                        created_at:
                          type: string
                          format: nullable
                        updated_at:
                          type: string
                          format: nullable
                        deleted_at:
                          type: string
                          format: nullable
                  first_page_url:
                    type: string
                    example: http://127.0.0.1:85/api/geo/countries?page=1
                  from:
                    type: number
                    example: 1
                  last_page:
                    type: number
                    example: 82
                  last_page_url:
                    type: string
                    example: http://127.0.0.1:85/api/geo/countries?page=82
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean
                  next_page_url:
                    type: string
                    example: http://127.0.0.1:85/api/geo/countries?page=2
                  path:
                    type: string
                    example: http://127.0.0.1:85/api/geo/countries
                  per_page:
                    type: number
                    example: 3
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: number
                    example: 3
                  total:
                    type: number
                    example: 246
